name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget $(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep browser_download_url | grep linux_amd64.tar.gz | cut -d '"' -f 4)
          tar -xvzf trivy_*_linux_amd64.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy Scan
        run: |
          chmod +x scan-k8s.sh
          ./scan-k8s.sh
