name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.2_linux_amd64.tar.gz
          tar -xvzf trivy_0.51.2_linux_amd64.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy Scan
        run: |
          chmod +x scan-k8s.sh
          ./scan-k8s.sh
